name: aviario_cm_flutter
description: Sistema veterinario completo Aviario C&M

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^11.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/icons/
